<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EDiffBundleAdminBundleEntityQuestionnaireProxy extends \EDiff\Bundle\AdminBundle\Entity\Questionnaire implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setTitre($titre)
    {
        $this->__load();
        return parent::setTitre($titre);
    }

    public function getTitre()
    {
        $this->__load();
        return parent::getTitre();
    }

    public function setNbQuestionsARepondre($nbQuestionsARepondre)
    {
        $this->__load();
        return parent::setNbQuestionsARepondre($nbQuestionsARepondre);
    }

    public function getNbQuestionsARepondre()
    {
        $this->__load();
        return parent::getNbQuestionsARepondre();
    }

    public function getMatiere()
    {
        $this->__load();
        return parent::getMatiere();
    }

    public function setMatiere(\EDiff\Bundle\AdminBundle\Entity\Matiere $matiere)
    {
        $this->__load();
        return parent::setMatiere($matiere);
    }

    public function getAnneeScolaire()
    {
        $this->__load();
        return parent::getAnneeScolaire();
    }

    public function setAnneeScolaire(\EDiff\Bundle\AdminBundle\Entity\AnneeScolaire $anneescolaire)
    {
        $this->__load();
        return parent::setAnneeScolaire($anneescolaire);
    }

    public function getClasse()
    {
        $this->__load();
        return parent::getClasse();
    }

    public function setClasse(\EDiff\Bundle\AdminBundle\Entity\Classe $classe)
    {
        $this->__load();
        return parent::setClasse($classe);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'titre', 'nb_questions_a_repondre', 'matiere', 'anneescolaire', 'classe');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}